# Generated by Django 4.1.6 on 2023-02-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentregisteration",
            old_name="Student_first_name",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="studentregisteration",
            old_name="Student_age",
            new_name="student_age",
        ),
        migrations.RenameField(
            model_name="studentregisteration",
            old_name="Student_exam_pass",
            new_name="student_exam_pass",
        ),
        migrations.RenameField(
            model_name="studentregisteration",
            old_name="Student_id",
            new_name="student_id",
        ),
        migrations.RenameField(
            model_name="studentregisteration",
            old_name="Student_mail",
            new_name="student_mail",
        ),
        migrations.RenameField(
            model_name="studentregisteration",
            old_name="Student_last_name",
            new_name="username",
        ),
    ]
